name: Build Zed for Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      - name: Add MSVC build tools to PATH
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install required dependencies
        run: |
          choco install cmake -y
          # Add other dependencies here if needed

      - name: Build (Release)
        run: cargo build --release

      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-build
          path: target/release/

      - name: (Optional) Run tests
        run: cargo test --release
