name: Build Zed for Windows

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Enable Windows long path support
      - name: Enable Windows Long Paths
        run: |
          Set-ItemProperty -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem' -Name 'LongPathsEnabled' -Value 1
        shell: pwsh

      # Enable Git long path support
      - name: Enable Git long paths
        run: git config --system core.longpaths true

      # Checkout to a short path to avoid directory nesting
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          path: src

      # Install Rust toolchain
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-pc-windows-msvc

      # Add MSVC build tools to PATH
      - name: Add MSVC build tools to PATH
        uses: ilammy/msvc-dev-cmd@v1

      # Install required dependencies (add others if needed)
      - name: Install CMake
        run: choco install cmake -y

      # Build (Release) using short path
      - name: Build (Release)
        run: cargo build --release
        working-directory: src

      # Archive build output
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: zed-windows-build
          path: src/target/release/

      # (Optional) Run tests using short path
      - name: (Optional) Run tests
        run: cargo test --release
        working-directory: src
